apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    svc: python-svc
spec:
  type: NodePort
  ports:
    - port: 97
      nodePort: 32183
      protocol: TCP
  selector:
    run: python