apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    svc: tomcat-svc
spec:
  type: NodePort
  ports:
    - port: 97
      nodePort: 32184
      protocol: TCP
  selector:
    run: tomcat