apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      run: zookeeper
  template:
    metadata:
      labels:
        run: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: library/zookeeper